spring:
  application:
    name: entbase
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/entbase?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: wm20031216.
  redis:
    host: localhost
    port: 6379
    password: wm20031216.
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

    mail:
    #
    host: smtp.qq.com
    #
    default-encoding: UTF-8
    #
    username: 3276327856@qq.com
    #
    password: snaquydrfzxudaea

    properties:
      mail:
        smtp:
          auth: true  #
          starttls: #
            enable: true
            required: true
  servlet:
    multipart:
      max-request-size: 2560MB
      max-file-size: 256MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

